version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:1
    ports:
    - 8090:8090 

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: frontend:1
    ports:
    - 3000:3000
    depends_on:
    - backend